spring:
  #处理swagger报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #静态资源处理
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      chain:
        #资源配链启动缓存，默认启动
        cache: true
        #启动资源链，默认禁用
        enabled: true
        #启用压缩资源（gzip，brotil）解析，默认禁用
        compressed: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600

  #thymeleaf
  thymeleaf:
    cache: false

  #数据源 用Hikari
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    password: zdk13696086376.
    hikari:
      #连接池名
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存货的最大时间 默认600000(10分钟) 这里设置为30分钟
      idle-timeout: 600000
      #最大连接数 默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间 0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      #连接超时时间 默认30秒
      connection-timeout: 30000
      #心跳机制 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #redis配置
  redis:
    host: 211.69.238.77
    password: zdk13696086376.
    port: 6379
    database: 1
    #连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞时间 默认-1
        max-wait: 1000ms
        #最大空闲连接，默认8
        max-idle: 200


  #RabbitMQ
  rabbitmq:
    #服务器
    host: 211.69.238.77
    #用户名
    username: admin
    #密码
    password: 123456
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1
      mandatory: true
    publisher-returns: true

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zdk.seckilldemo.pojo

#日志  mybatis SQL打印 (方法接口所在的包) 不是Mapper.xml的包
logging:
  level:
    com.zdk.seckilldemo.mapper: debug
